### ISSUE TITLE
Refresh access Token

### ISSUE THREAD

**Issue by diofeher** [pokitdok/pokitdok-ruby#19]
Hey guys, in my application after a while I receive Oauth2 : Unauthorized errors. It looks that the access token was expired. I see that you have a TODO to put in the lib, but I see pokitdok-python has this feature to refresh the token.

What is the current workaround to that issue?

**Comment by wootencl** [comment]
Hi @diofeher. Good catch. Funny enough I'm hoping to address that situation this week and add needed functionality. Sadly there is currently no workaround outside of manually refreshing your auth token :disappointed:

**Comment by diofeher** [comment]
Awesome @wootencl. I was going to work on that but I will just wait as this is going to be worked and it's not urgent for us :) thanks!

**Comment by wootencl** [comment]
@diofeher A fairly large restructure/rewrite of the ruby client was just released. It should now have the ability to catch whether or not your token has expired and refresh it if it has.

Closing this issue as this should be resolved in version 0.8.0

**Comment by diofeher** [comment]
Awesome, thanks!
