### ISSUE TITLE
pokitdok-ruby 0.8.0 incompatible with oauth2 1.3.0

### ISSUE THREAD

**Issue by rahearn** [pokitdok/pokitdok-ruby#23]
Everything works great when I have oauth2 1.2.0 installed, but on updating to 1.3.0 pokitdok is unable to retrieve a token as part of `PokitDok::PokitDok.new(client_id, secret)`

Error received is:

> OAuth2::Error: invalid_request: Malformed Authorization header: 
{"error": "invalid_request: Malformed Authorization header"}

**Comment by denisekgosnell** [comment]
@rahearn Thank you for letting us know. We found the following breaking change in the changelog from oauth1 1.2.0 to 1.3.0:

```Default to header-based authentication when getting a token from an authorization code (@maletor)```
https://github.com/intridea/oauth2/blob/master/CHANGELOG.md#130---2016-12-28

We are looking into this a bit deeper, but our theory is that anyone running with defaults, now have new defaults.  For the immediate future, can you stay on 1.2.0 or try setting auth_scheme  to :basic_auth?

In the meantime, we will do some more digging and let you know what else we find.

**Comment by rahearn** [comment]
Yes, I froze oauth2 at 1.2.0 for now.

**Comment by JaredCorduan** [comment]
@rahearn Thanks again for letting us know!
I think this should fix your problem: https://github.com/pokitdok/pokitdok-ruby/tree/PLATFORM-5398
I'll let you know when I've merged to master and cut a new :gem:

**Comment by JaredCorduan** [comment]
@rahearn I just released version 0.8.1, let me know if that fixes your issue with oauth2 1.3.0.

**Comment by rahearn** [comment]
@JaredCorduan yes, 0.8.1 looks like it's working with oauth2 1.3.0. Thanks.
