### ISSUE TITLE
Issuing an eligibility request with a last name but no first name returns an HTML error page

### ISSUE THREAD

**Issue by shipstar** [pokitdok/pokitdok-ruby#3]
The following request returns an HTML 500 error page instead of a Ruby Error/Exception subclass:

    pd = PokitDok::PokitDok.new(ENV['POKITDOK_KEY'], ENV['POKITDOK_SECRET'])

    query = {
      member: {
        last_name: "Doe"
      }
    }

    pd.eligibility(query)

Adding `first_name` makes it a valid request (at least in dev mode) and omitting `last_name` or `member` entirely returns an `OAuth2::Error` as expected. (Close enough, anyway.)

**Comment by riney** [comment]
Hm. It certainly shouldn't be doing that! I'll check with the platform team, since the wrong stuff is coming back from the API (you should always get a JSON-formatted response with a semi-polite error message)

**Comment by riney** [comment]
Alright, turns out there was a little validation glitch. Fix should go out this week. Of course, in a realistic scenario, you'd need a first name, last name, a member id, and a trading partner id, but it should always return a proper error payload no matter what. Thanks so much for letting me know.

**Comment by shipstar** [comment]
Right -- I'll definitely make those fields required on my frontend. Was just trying to see what kinds of errors came back for missing data and caught that edge case.




Thanks!

**Comment by riney** [comment]
Okay, our Platform god @corbinbs just shipped an update to the validation. So now
    pd.eligibility({
        "member": {
            "last_name": "CORBIN",
        },
        "trading_partner_id": "MOCKPAYER"
    })
Will return
    "data": {
        "errors": {
            "validation": {
                "member": {
                    "first_name": [
                        "This field is required."
                    ]
                }
            }
        }
    }

**Comment by corbinbs** [comment]
@shipstar : thanks again for the validation error bug report!
